### ISSUE TITLE
JPA entity listener @PostLoad  method not getting called

### ISSUE THREAD

**Issue by dtuzikov** [Impetus/kundera#234]
Hi,
I have a entity with @EntityListeners(MyHandler.class) annotation specified and a class MyHandler.class with @PostLoad annotated method in it. After calling em.refresh(entity) or em.find(entityClass,entityPk) post-load method not getting called. However, @PrePersist annotation works fine.

**Comment by mevivs** [comment]
Can be clubbed with

https://github.com/impetus-opensource/Kundera/issues/217

?

-Vivek

**Comment by dtuzikov** [comment]
When persisting an entities without children, @PrePersist annotation works fine. It seems to me, that @PostLoad annotations are not processed at all.

**Comment by mevivs** [comment]
Fixed in current trunk.

-Vivek

**Comment by mevivs** [comment]
Fixed and releasing with 2.6.
-Vivek

**Comment by dtuzikov** [comment]
Not fixed, @PostLoad not working

**Comment by mevivs** [comment]
A test case added to validate @PostLoad on current trunk. Please refer above commit.

-Vivek

**Comment by dtuzikov** [comment]
Not fixed.
Method EntityEventDispatcher.fireEventListeners(..) works well in test, but it's not getting fired when loading entities, so @PostLoad not working. (version 2.7)

**Comment by mevivs** [comment]
Could you please provide a sample junit with what's exactly not working?

-Vivek

**Comment by mevivs** [comment]
Verified. pre/post events are not fixed for finders.

**Comment by mevivs** [comment]
Fixed in current trunk. Releasing with 2.7.1.

Please verify.

-Vivek
